/**
 * Property-Based Tests for ULID Lexicographic Ordering
 *
 * **Validates: Requirements 30.7**
 *
 * Property 18: ULID Lexicographic Ordering — For any two entities created in
 * sequence (t1 < t2), the ULID generated at t2 SHALL be lexicographically
 * greater than the ULID generated at t1, ensuring time-sorted queries return
 * results in creation order.
 */

import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { generateId, extractTimestamp, isValidUlid } from './ulid';

describe('Property 18: ULID Lexicographic Ordering', () => {
  /**
   * Property 1: For any two timestamps t1 < t2, generateId(t1) < generateId(t2) lexicographically.
   *
   * **Validates: Requirements 30.7**
   */
  it('ULIDs generated at different timestamps are lexicographically ordered (t1 < t2 => id1 < id2)', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 281474976710655 }),
        fc.integer({ min: 1, max: 281474976710655 }),
        (a, b) => {
          const t1 = Math.min(a, b);
          const t2 = Math.max(a, b);

          // Skip when timestamps are equal — covered by the monotonic property
          fc.pre(t1 < t2);

          const id1 = generateId(t1);
          const id2 = generateId(t2);

          expect(id1 < id2).toBe(true);
        },
      ),
      { numRuns: 100 },
    );
  });

  /**
   * Property 2: For any ULID generated by generateId(), isValidUlid() returns true.
   *
   * **Validates: Requirements 30.7**
   */
  it('any ULID produced by generateId() passes isValidUlid() validation', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 281474976710655 }),
        (seedTime) => {
          const id = generateId(seedTime);
          expect(isValidUlid(id)).toBe(true);
        },
      ),
      { numRuns: 100 },
    );
  });

  /**
   * Property 3: For any ULID generated with a seed time, extractTimestamp() returns
   * a value that is at least the seed time (monotonic factory may advance the clock)
   * and within the valid ULID timestamp range (0 to 2^48 - 1).
   *
   * **Validates: Requirements 30.7**
   */
  it('extractTimestamp() returns a value within the expected ULID timestamp range', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 281474976710655 }),
        (seedTime) => {
          const id = generateId(seedTime);
          const extracted = extractTimestamp(id);

          // The monotonic factory guarantees the extracted timestamp is >= seedTime
          // (it may be higher if the factory's internal clock is ahead)
          expect(extracted).toBeGreaterThanOrEqual(seedTime);

          // Must be within valid ULID timestamp range (48-bit)
          expect(extracted).toBeGreaterThanOrEqual(0);
          expect(extracted).toBeLessThanOrEqual(281474976710655);
        },
      ),
      { numRuns: 100 },
    );
  });

  /**
   * Property 4: Multiple ULIDs generated at the same timestamp are still
   * lexicographically ordered (monotonic guarantee).
   *
   * **Validates: Requirements 30.7**
   */
  it('multiple ULIDs at the same timestamp are monotonically increasing', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 1, max: 281474976710655 }),
        fc.integer({ min: 2, max: 10 }),
        (seedTime, count) => {
          const ids: string[] = [];
          for (let i = 0; i < count; i++) {
            ids.push(generateId(seedTime));
          }

          // Each successive ID should be lexicographically greater than the previous
          for (let i = 1; i < ids.length; i++) {
            expect(ids[i - 1] < ids[i]).toBe(true);
          }
        },
      ),
      { numRuns: 100 },
    );
  });
});
